name: flutter_native_splash
description: Automatically generates native code for adding splash screens in Android and iOS. Customize with specific platform, background color and splash image.
version: 0.1.10
homepage: https://github.com/henriquearthur/flutter_native_splash

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  yaml: ^3.1.0
  image: ^3.1.3
  color: ^3.0.0
  xml: ^5.4.1

dev_dependencies:
  pedantic: ^1.11.1
